---
- name: Ansible Playbook to Deploy Mesos Masters/Slaves and Marathon
  hosts: localhost 
  sudo: yes
  gather_facts: yes
  
  tasks:
    
    - name: Add Repository Key
      command: "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E56151BF"
      tags: add key

    - name: Add Repository for Mesos 
      apt_repository: repo='deb http://repos.mesosphere.com/ubuntu vivid  main' state=present
      tags: add_repo
   
    - name: Run system update
      apt: update_cache=yes
      tags: update_system

    - name: Installing packages
      apt: name={{ item }} state=present force=yes
      with_items:
        - mesos
        - marathon

    - name: Update zookeper configuration
      raw: "sudo chmod 666  /etc/zookeeper/conf/myid; sudo echo 1 > /etc/zookeeper/conf/myid"
      when: ansible_eth1.ipv4.address == "10.1.200.11"
      tags: zookeeper_value
      
    - name: Update zookeper configuration
      raw: "sudo chmod 666  /etc/zookeeper/conf/myid; sudo echo 2 > /etc/zookeeper/conf/myid"
      when: ansible_eth1.ipv4.address == "10.1.200.12"
      tags: zookeeper_value

    - name: Update zookeper configuration
      raw: "sudo chmod 666  /etc/zookeeper/conf/myid; sudo echo 3 > /etc/zookeeper/conf/myid"
      when: ansible_eth1.ipv4.address == "10.1.200.13"
      tags: zookeeper_value
    
    - name: Push zookeper configuration file
      copy: src=templates/zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg force=yes
      tags: push_conf
    
    - name: Push /etc/mesos/zk
      copy: src=templates/zk.j2 dest=/etc/mesos/zk force=yes
      tags: push_conf2
    
    - name: Fix the etc/hosts issue
      lineinfile: dest=/etc/hosts regexp='^127.0.1.1' line='#127.0.1.1'
      tags: etcfix
    
    - name: Put the right values in /etc/hosts
      lineinfile: dest=/etc/hosts line="{{ansible_eth1.ipv4.address}} {{ansible_hostname}}" state=present
      tags: putfix
      
    - name: Restart zookeeper service 
      service: name=zookeeper state=restarted enabled=yes
      tags: Restarting zookeeper

    - name: Pushing quorum value of 2 
      raw: "sudo chmod 666 /etc/mesos-master/quorum; sudo echo 2 > /etc/mesos-master/quorum"
      tags: push_conf3
    
    - name: Disable slave service
      service: name=mesos-slave state=stopped enabled=no
      tags: slave_stop
    
    - name: Start up master service
      service: name={{ item }} state=restarted enabled=yes
      with_items: 
        - mesos-master
        - marathon
      tags: start_services
