---
- name: Ansible Playbook to Deploy Mesos Masters/Slaves and Marathon
  hosts: localhost 
  remote_user: vagrant
  sudo: yes
  gather_facts: yes
  #serial: "10%"
  
  tasks:
    - name: Add Repository Key
      command: "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E56151BF"
      tags: add key

    - name: Add Repository for Mesos 
      apt_repository: repo='deb http://repos.mesosphere.com/ubuntu vivid main' state=present
      tags: add_repo

    - name: Run system update
      apt: update_cache=yes
      tags: update_system

    - name: Installing packages
      apt: name={{ item }} state=installed
      with_items:
        - mesos
    
    - name: Stop zookeeper service
      service: name=zookeeper state=stopped enabled=no
      tags: zookeeper_stop
    
    - name: Push /etc/mesos/zk
      copy: src=templates/zk.j2 dest=/etc/mesos/zk force=yes
      tags: push_conf

    - name: Disable mesos-master service
      service: name=mesos-master state=stopped enabled=no
      tags: mesos-master_stop
     
    - name: Fix the etc/hosts issue
      lineinfile: dest=/etc/hosts regexp='^127.0.1.1' line='#127.0.1.1'
      tags: etcfix

    - name: Put the right values in /etc/hosts
      lineinfile: dest=/etc/hosts line="{{ansible_eth1.ipv4.address}} {{ansible_hostname}}" state=present
      tags: putfix

    - name: Restart slave service
      service: name=mesos-slave state=restarted enabled=yes
      tags: slave_restarted

